services:
    - mysql
language: python
python:
    - "3.7"
install:
    - sudo apt update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
      # Useful for debugging any issues with conda
    - conda info -a
    - conda env create -f environment-dev.yml
    - conda activate nepc-dev
    - pip install -e .
    #- pip install pylint-exit
    - pip install anybadge
    #- pip install docstr-coverage
    - mkdir ${HOME}/.mysql
    - echo "[client]\nuser=root" > ${HOME}/.mysql/defaults
    - python nepc/mysql/build.py --travis

script:
      # test
    - pytest --cov=nepc tests/ --travis
    #- pytest --cov=nepc tests/ | tee pytest.txt
    #- score=$(cat pytest.txt | grep TOTAL | grep -o -P '[0-9]*(\.[0-9]*)?(?=%)')
    #- echo "test coverage is ${score}%"
    #- anybadge --label=pytest --value=$score --suffix='%' --file=pytest.svg 50=red 60=orange 80=yellow 100=green
      # docs
      #- cd docs
      #- make html
      #- rsync -rl _build/html/ /srv/shiny-server/nepc/doc/ --delete
      #- cd ..
      #- docstr-coverage nepc | tee docstr.txt || true
      #- score=$(cat docstr.txt | tail -n 1 | grep -Eo '[+-]?[0-9]+([.][0-9]+)?')
      #- echo "docstr-coverage score was ${score}%"
      #- anybadge --label=doc --value=$score --suffix='%' --file=sphinx.svg 50=red 60=orange 80=yellow 100=green
      # lint
      #- pylint --output-format=text nepc/ | tee pylint.txt || pylint-exit $?
      #- score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
      #- echo "Pylint score was $score"
      #- anybadge --value=$score --file=pylint.svg pylint
