name: nepc
channels:
        - defaults
        - conda-forge
dependencies:
        - ipython=7.3.0
        - ipython_genutils=0.2.0
        - jpeg=9b
        - jupyter=1.0.0
        - jupyter_client=5.2.4
        - numpy=1.16.2
        - pandas=0.24.2
        - pip=19.0.3
        - python=3.7.2
        - scipy=1.2.1
        - matplotlib
        - tabulate=0.8.3
        - pip
        - pip:
                - mysql-connector-python==8.0.11
                - pdfminer.six==20181108
                - pdfplumber==0.5.11
