name: nepc
channels:
        - defaults
        - conda-forge
dependencies:
        - ipython=7.3.0
        - ipython_genutils=0.2.0
        - jupyter
        - jupyter_client
        - numpy=1.16.2
        - pandas=0.24.2
        - python=3.7.2
        - matplotlib
        - pip=19.0.3
        - pip:
                - mysql-connector-python==8.0.17
