name: nepc-ci
channels:
        - conda-forge
dependencies:
        - numpy
        - pandas
        - python==3.7
        - matplotlib
        - pytest
        - pytest-cov
        - pip
        - pip:
                - mysql-connector-python==8.0.17
